Repository googleapis/python-analytics-admin, pull requests merged in 2021-01, with the labels that each got.

#30 chore: update templates
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .trampolinerc
  LICENSE
  docs/_static/custom.css
  noxfile.py
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: partial

#29 fix!: remove unused fields from `EnhancedMeasurementSettings`
  .coveragerc
  docs/admin_v1alpha/analytics_admin_service.rst
  docs/admin_v1alpha/services.rst
  docs/admin_v1alpha/types.rst
  google/analytics/admin_v1alpha/services/analytics_admin_service/async_client.py
  google/analytics/admin_v1alpha/services/analytics_admin_service/client.py
  google/analytics/admin_v1alpha/services/analytics_admin_service/pagers.py
  google/analytics/admin_v1alpha/services/analytics_admin_service/transports/grpc.py
  google/analytics/admin_v1alpha/services/analytics_admin_service/transports/grpc_asyncio.py
  google/analytics/admin_v1alpha/types/analytics_admin.py
  google/analytics/admin_v1alpha/types/resources.py
  scripts/fixup_admin_v1alpha_keywords.py
  synth.metadata
  tests/unit/gapic/admin_v1alpha/test_analytics_admin_service.py
Labels: api: analyticsadmin, cla: yes, context: partial

#36 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: analyticsadmin, cla: yes
