Repository googleapis/python-analytics-admin, pull requests merged in 2021-04, with the labels that each got.

#47 chore: start tracking obsolete files
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#48 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#49 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full, samples

#50 chore: prevent normalization of semver versioning
  setup.py
Labels: api: analyticsadmin, cla: yes

#52 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  google-analytics-admin-v1alpha-py.tar.gz
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: partial

#53 chore(revert): revert preventing normalization
  setup.py
Labels: api: analyticsadmin, cla: yes
