Repository googleapis/python-analytics-admin, pull requests merged in 2021-06, with the labels that each got.

#74 docs: add samples for Google Analytics property management methods
  samples/properties_create.py
  samples/properties_create_test.py
  samples/properties_delete.py
  samples/properties_delete_test.py
  samples/properties_firebase_links_create.py
  samples/properties_firebase_links_create_test.py
  samples/properties_firebase_links_delete.py
  samples/properties_firebase_links_delete_test.py
  samples/properties_firebase_links_list.py
  samples/properties_firebase_links_list_test.py
  samples/properties_firebase_links_update.py
  samples/properties_firebase_links_update_test.py
  samples/properties_get.py
  samples/properties_get_test.py
  samples/properties_google_ads_links_create.py
  samples/properties_google_ads_links_create_test.py
  samples/properties_google_ads_links_delete.py
  samples/properties_google_ads_links_delete_test.py
  samples/properties_google_ads_links_list.py
  samples/properties_google_ads_links_list_test.py
  samples/properties_google_ads_links_update.py
  samples/properties_google_ads_links_update_test.py
  samples/properties_list.py
  samples/properties_list_test.py
  samples/properties_update.py
  samples/properties_update_test.py
Labels: api: analyticsadmin, cla: yes, samples

#78 fix: exclude docs and tests from package
  setup.py
Labels: api: analyticsadmin, automerge, cla: yes

#80 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: analyticsadmin, automerge, cla: yes

#83 chore: move non-cloud package to staging bucket
  .kokoro/docs/common.cfg
  owlbot.py
Labels: api: analyticsadmin, cla: yes
